[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; connect-src 'self' https://devmate-fghed0fgatfwd3ga.centralindia-01.azurewebsites.net; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' https: data:; img-src 'self' data: https:; font-src 'self' data: https:;"
    X-Frame-Options = "DENY" 
    X-Content-Type-Options = "nosniff"

[[redirects]]
  from = "/api/*"
  to = "https://devmate-fghed0fgatfwd3ga.centralindia-01.azurewebsites.net/api/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
